# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportTabToCSV
                                 A QGIS plugin
 Esporta la tabella del layer vettoriale selezionato su un file CSV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-24
        copyright            : (C) 2024 by dr. Geol. Faustino Cetraro
        email                : geol-faustino@libero.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ExportTabToCSV class from file ExportTabToCSV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .export_tab_to_csv import ExportTabToCSV
    return ExportTabToCSV(iface)
